name: ci-cd
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm install -g firebase-tools
          firebase deploy --token ${{ secrets.TOKEN }}
